### ISSUE TITLE
[FEAT] AddFeedBackMemberView UI 구현

### ISSUE THREAD

**Issue by Guel-git** [DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple#12]
## 💡 Issue
<img src="https://user-images.githubusercontent.com/81340603/196371524-ec212ba3-adb1-4381-abf4-e1ac654b8993.png" width=200px />
AddFeedBackMemberView UI 구현

## 📝  Todo
- [x] 디렉토리 & 파일 생성
- [x] 상단 라벨
- [x] MemberCollectionViewCell -> Button으로
- [x] MemberCollectionView (Global에)

**Comment by MMMIIIN** [comment]
화이팅화이팅 !
