### ISSUE TITLE
[FEAT] CAGradientLayer 박살내기 실험

### ISSUE THREAD

**Issue by MMMIIIN** [DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple#16]
## 💡 Issue

<img width="686" alt="image" src="https://user-images.githubusercontent.com/78677571/196587327-b71076b8-3dcf-41a3-bc2f-1f24469f3bc4.png">
<img width="438" alt="image" src="https://user-images.githubusercontent.com/78677571/196587357-98af35e9-f894-4c8f-8574-8123f3fd1b9a.png">

메인버튼과 키워드 등에 사용되는 그라데이션 문제를 해결하기 위한 실험을 진행합니다.

## 📝  Todo
- [ ] 키워드 UI 만들기

**Comment by dangsal** [comment]
이슈 네이밍... 찡ㅅ끘 ㅎㅎ

**Comment by MMMIIIN** [comment]
> 이슈 네이밍... 찡ㅅ끘 ㅎㅎ

급했나봐여.. 하하
