### ISSUE TITLE
[BUG] 리더의 경우 키워드 개수가 많아지면 키워드 마지막 줄이 가려지는 버그

### ISSUE THREAD

**Issue by dangsal** [DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple#200]
## 📜 Bug Description

 리더의 경우 키워드 개수가 많아지면 키워드 마지막 줄이 가려지는 버그입니다.

## 📍 Bug View

Home

## 🐞 Bug Condition

- 리더일 경우
- 키워드가 꽉찰때

## 📷 Bug Screenshot

<img src = "https://user-images.githubusercontent.com/59243274/204743408-1ccc7950-b234-4310-9927-9ae11c0d3773.png" width = "350">

**Comment by seongmin221** [comment]
이잉 이거 백로그에서 제가 가져갔는데 제가 해도 될까용~?
