### ISSUE TITLE
[ADD] 회고시작 알림 View 구현

### ISSUE THREAD

**Issue by MMMIIIN** [DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple#23]
## 💡 Issue

회고 시작 알림 View를 구현합니다
<img width="192" alt="image" src="https://user-images.githubusercontent.com/78677571/196836083-3a114c95-6c7a-42b7-8231-1291a2e2f021.png">

## 📝  Todo
- [ ] blur 처리된 view올리기
- [ ] 내용 표시

**Comment by dangsal** [comment]
이슈 네이밍.. 찡긋

**Comment by MMMIIIN** [comment]
> 이슈 네이밍.. 찡긋

와우... 나 왜그랬지...?? 감사합니다..
