### ISSUE TITLE
[SETTING] 컬러 exxtension 과 폰트 extension을 추가합니다

### ISSUE THREAD

**Issue by dangsal** [DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple#6]
## 💡 Issue

컬러 exxtension 과 폰트 extension을 추가합니다

## 📝  Todo
- [ ] todo !
- [x] 컬러 추가
- [x] 폰트 추가
- [x] pr날리기

**Comment by MMMIIIN** [comment]
감사합니다 ! 빠이팅 ~~~!!!!
