### ISSUE TITLE
[FEAT] 메인 뷰 구현

### ISSUE THREAD

**Issue by seongmin221** [DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple#8]
## 💡 Issue

<img src="https://user-images.githubusercontent.com/72431640/196348828-c351372b-1357-4131-85af-d53698e9087a.png" width="300">

이 뷰의 전체적인 UI와 키워드 간 간격 조절하는 알고리즘을 구현하기 위한 이슈입니닷

## 📝  Todo
- [ ] UI 구성
- [ ] 리더와 멤버 분기처리
- [ ] 키워드 간 간격 조정 알고리즘

**Comment by MMMIIIN** [comment]
가보자고 가보자고 화이팅 !!
